### PR TITLE
Remove old, unused files

### PR DESCRIPTION
**Pull request by luisremis**

### CODE REVIEW

**Comment by vishakha041** [comment]
Does this also remove the folder these files are in? Those were the only two files in that folder

**Comment by vishakha041** [comment]
There is also still RWLock.h and arch.h files which I think are not needed anymore. YOu can change this one to code cleanup branch and put two commits as far as I can tell right now

**Comment by luisremis** [comment]
Good suggestion. I removed those files as well.

**Comment by luisremis** [comment]
> Does this also remove the folder these files are in? Those were the only two files in that folder

Yes, it does.

**Pull request merged**
