### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by vishakha041**
Fixes to some reported issues like error on empty results

### CODE REVIEW

**Comment by luisremis** [comment]
Also, it would be great to have python tests for this kind of bug fixes, even if similar to the unit tests you have for c++

**Comment by vishakha041** [comment]
Do you want me to merge this fix before the VCL changes or after?

**Comment by luisremis** [comment]
Looks good to go! Conflicts should be straight forward to fix. Either adding and extra commit for the conflict fix or amending the last commit (with the tests cases) should be fine.

**Comment by vishakha041** [comment]
Should be good to merge now. Take a look. Passes on my system with the new test hierarchy.

**Pull request merged**
